# This workflow will generate the docs on each push, and publish them on GitHub Pages if the branch is "main".

name: docs

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          # Only use python version matching libboost_python*.so lib
          # 3.8 for ubuntu-20.04
          # 3.10 for ubuntu-22.04
          # ...
          # Unfortunately, 3.x does not work for ubuntu-latest
          python-version: "3.8"

      - name: Install package
        run: |
          sudo apt install pandoc
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python setup.py install

      - name: Build Sphinx documentation
        run: |
          sphinx-build -a -E -b html docs build

      - name: Deploy Sphinx documentation on Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: github.ref == 'refs/heads/main'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/
