# This workflow will generate the docs on each push, and publish them on GitHub Pages if the branch is "main".

name: docs

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # Only use python version matching libboost_python*.so lib
        # 3.8 for ubuntu 20.04
        # 3.10 for ubuntu 22.04
        # ...
        # Unfortunately, 3.x does not work for ubuntu-latest
        python-version: ["3.8"]
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # .github/workflows/build.yml
    # https://github.com/actions/setup-python#caching-packages-dependencies
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # Caching dependencies

#    - name: Install graphviz
#      run: |
#        sudo apt install graphviz

    - name: Install package
      run: |
#        python -m pip install --upgrade pip
#        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
#        python setup.py install
         poetry install --with docs

    - name: Build Sphinx documentation
      run: |
        #sphinx-build -a -E -b html docs build
        poetry run sphinx-build -a -E -b html docs build

    - name: Deploy Sphinx documentation on Github Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      if: github.ref == 'refs/heads/main'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build/
